apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-varsel-firewall
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: false
    #path: /internal/metrics
  ingresses:
    - https://altinn-varsel-firewall.dev.nav.no
  env:
    - name: NOTIFICATION_AGENCY_ENDPOINT_URL
      value: "https://tt02.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: tt02.altinn.no
# WARNING: Ikke kommenter ut før notifikasjon-ekstern-varsling har
# skrudd på Azure AD. Ellers må vi tvinge fram regenerering av
# azure-ad-koblinger.
#    inbound:
#      rules:
#        - application: notifikasjon-ekstern-varsling