apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-varsel-firewall
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: false
    #path: /internal/metrics
  env:
    - name: NOTIFICATION_AGENCY_ENDPOINT_URL
      value: "https://www.altinn.no/ServiceEngineExternal/NotificationAgencyExternalBasic.svc"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: www.altinn.no
#    inbound:
#      rules:
#        - application: notifikasjon-ekstern-varsling
