name: ci/cd
on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - run: mvn -B package

      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: fager
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/bom.json

      - uses: nais/deploy/actions/deploy@v1
        name: "deploy dev-gcp"
        if: github.ref == 'refs/heads/main' || github.ref== 'refs/heads/upgrade_dependencies'
        env:
          IMAGE: ${{ steps.gar-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml

      - uses: nais/deploy/actions/deploy@v1
        name: "deploy prod-gcp"
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE: ${{ steps.gar-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp.yaml
