name: ci/cd
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/altinn-varsel-firewall


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - run: mvn -B package

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        if: github.event_name == 'pull_request'
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          title: ":space_invader: jacococo go nogo :space_invader:"

      - name: Login to GitHub Package Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ github.repository }}/altin-varsel-firewall:latest
          cache-to: type=inline

      - uses: nais/deploy/actions/deploy@v1
        name: "deploy dev-gcp"
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE: ${{env.IMAGE}}:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
